### PR TITLE
#1 - test class to demonstrate error

### LINKED ISSUE #1: parsing of string does not succeed
**Describe the bug**
Given the simple URL from [pds-api 54](https://github.com/NASA-PDS/pds-api/issues/54) `/products?q="lid eq *text*"` and expectation (acceptance criteria), the registry-api-service when nuts and blew up with out of memory. Tracked it down to this module. Turns out there is a simple infinite loop in [ANTLR](https://www.antlr.org/index.html) 4.9.2 and earlier that is most likely a fault of the language or how it is being parsed because the [ANTL FAQ](https://github.com/antlr/antlr4/blob/4.9.2/doc/faq/getting-started.md) suggests that not terminating the stream is the biggest problem and the infinite loop is caused by never finding the end of the stream even though all data has been read.

**To Reproduce**
Run/Debug in Eclipse `api.pds.nasa.gov.api_search_query_lexer.TestParsing`.

**Expected behavior**
TestParsing should run to completion and successfully parse the `lid eq *text*` string without running out of memory.

**Version of Software Used**
ANTLR 4.3, 4.7, 4.9.

### PR DESCRIPTION
**Pull request by al-niessner**
Closes #1

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Please review the changes to grammar. I am pretty sure they are wrong, but the test completes now in various forms with and without quotes etc.

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

My mistake. The double escaping does not work at all:

```
curl --location --request GET http://localhost:8080/products?q="lid%20eq%20\"*pdart14_meap*\""
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
```

From the registry-api-service:

```
2021-03-30 20:31:28.899 DEBUG 341 --- [0.3-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received [GET /products?q=lid%20eq%20"*pdart14_meap*" HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.68.0
Accept: */*

]
2021-03-30 20:31:28.901  INFO 341 --- [0.3-8080-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in the request target [/products?q=lid%20eq%20"*pdart14_meap*"]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:491) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Probably need to use HTML escaping for the quoting in the string.

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Ready for review.

**Comment by al-niessner** [comment]
Also, after you approve it, will you please do another release of it. I will then update the registry-api-service to use the new version.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner 

So that we don't need to do pull request/review procedure, can you generate the antlr jar locally and use it in your API development server ? The development process will be quicker this way until everything is stabilized.

Regarding this pull request. Did you check that every is not considered as VALUE in the grammar (and nothing get catched anymore as STRING or NUMBER) ? 

At last, regarding your comment above on " quote in the query. We did not have issue with that yet by encoding the url, for example:
Request {{baseUrl}}/collections?limit=10&q=(pds/Primary_Result_Summary/pds/processing_level eq "Raw")

is encoded 'https://pds-gamma.jpl.nasa.gov/api/collections?limit=10&q=(pds/Primary_Result_Summary/pds/processing_level%20eq%20%22Raw%22)'

For request examples, you can refer to the postman test suite: https://github.com/NASA-PDS/registry-api-service/blob/master/src/test/resources/postman_collection.json
You can import this file in postman as described in the readme https://github.com/NASA-PDS/registry-api-service#use-postman

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Ready for review. Updated TestParser to verify that each type (NUMBER, STRINGVAL, VALUE) all parse correctly.

**Review by tloubrieu-jpl — APPROVED** [review]
Thanks Al, that is good to have the unit tests. I converted them to junit test so that they run automatically when we build. I also upgraded the version to avoid conflicts with the pre-existing version.

**Pull request merged**
